name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Buat commit kosong
        run: |
          git config --local user.email "rim260705@gmail.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Auto commit: $(date)"
          git push
